## A.I. Assignment 5

## Learning Goals

By the end of this lab, you should be able to:
* Get more familiar with tensors in pytorch 
* Create a simple multilayer perceptron model with pytorch
* Visualise the parameters


### Task

Build a fully connected feed forward network that adds two bits. Determine the a propper achitecture for this network (what database you use for this problem? how many layers? how many neurons on each layer? what is the activation function? what is the loss function? etc)

Create at least 3 such networks and compare their performance (how accurate they are?, how farst they are trained to get at 1 accuracy?)

Display for the best one the weights for each layer.


In [155]:
import torch
import torch.nn as nn
from collections import OrderedDict

In [156]:
model1 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 2)),  
    ('Sigmoid', nn.Sigmoid()),    
    ('output', nn.Linear(2, 2)),  
    ('Sigmoid', nn.Sigmoid())
]))
print(model1)

data_in1 = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
print(data_in1)

data_target1 = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float)
print(data_target1)

criterion1 = nn.MSELoss()
optimizer1 = torch.optim.SGD(model1.parameters(), lr=0.1)

for epoch in range(10000):
    outputs1 = model1(data_in1)
    loss1 = criterion1(outputs1, data_target1)
    
    optimizer1.zero_grad()  
    loss1.backward()          
    optimizer1.step()         
    
    predicted_classes1 = (outputs1.round() == data_target1)
    accuracy1 = predicted_classes1.all(dim=1).sum() / len(data_target1)
    if (epoch+1) % 1000 == 0:
        print(f'Epoch {epoch+1} Loss: {loss1.item()} Accuracy: {accuracy1*100}%')
    if accuracy1 == 1:
        print(f"Model 1 reached 100% accuracy at epoch {epoch+1}")
        break

print(outputs1)
predicted1 = torch.round(outputs1)
correct1 = (predicted1 == data_target1).all(dim=1).sum()
total1 = data_target1.size(0)
accuracy1 = correct1 / total1
print(f'Model Accuracy: {accuracy1*100}%')  

    
print(f"Model weights:")
for name, param in model1.named_parameters():
    if param.requires_grad:
        print(name, param.data)

Sequential(
  (hidden): Linear(in_features=2, out_features=2, bias=True)
  (Sigmoid): Sigmoid()
  (output): Linear(in_features=2, out_features=2, bias=True)
)
tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])
Epoch 1000 Loss: 0.15771432220935822 Accuracy: 50.0%
Epoch 2000 Loss: 0.14849580824375153 Accuracy: 50.0%
Epoch 3000 Loss: 0.13349276781082153 Accuracy: 75.0%
Epoch 4000 Loss: 0.108953095972538 Accuracy: 75.0%
Model 1 reached 100% accuracy at epoch 4383
tensor([[-0.1738,  0.4998],
        [ 0.1070,  0.6199],
        [ 0.1035,  0.6023],
        [ 0.9766,  0.2626]], grad_fn=<AddmmBackward0>)
Model Accuracy: 100.0%
Model weights:
hidden.weight tensor([[-0.8698, -0.9363],
        [ 1.9595,  1.9578]])
hidden.bias tensor([ 0.2148, -3.9993])
output.weight tensor([[-0.2687,  2.2691],
        [-1.1694, -1.4872]])
output.bias tensor([-0.0659,  1.1734])


In [157]:
model2 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 5)),  
    ('ReLU', nn.ReLU()),    
    ('output', nn.Linear(5, 2)),  
    ('Sigmoid', nn.Sigmoid())
]))
print(model2)

data_in2 = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
print(data_in2)

data_target2 = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float)
print(data_target2)

criterion2 = nn.MSELoss()
optimizer2 = torch.optim.SGD(model2.parameters(), lr=0.1)

for epoch in range(10000):
    outputs2 = model2(data_in2)
    loss2 = criterion2(outputs2, data_target1)
    
    optimizer2.zero_grad()  
    loss2.backward()          
    optimizer2.step()         
    
    predicted_classes2 = (outputs2.round() == data_target2)
    accuracy2 = predicted_classes2.all(dim=1).sum() / len(data_target1)
    if (epoch+1) % 1000 == 0:
        print(f'Epoch {epoch+1} Loss: {loss2.item()} Accuracy: {accuracy2*100}%')
    if accuracy2 == 1:
        print(f"Model 2 reached 100% accuracy at epoch {epoch+1}")
        break

print(outputs2)
predicted2 = torch.round(outputs2)
correct2 = (predicted2 == data_target2).all(dim=1).sum()
total2 = data_target2.size(0)
accuracy2 = correct2 / total2
print(f'Model Accuracy: {accuracy2*100}%')  

    
print(f"Model weights:")
for name, param in model2.named_parameters():
    if param.requires_grad:
        print(name, param.data)

Sequential(
  (hidden): Linear(in_features=2, out_features=5, bias=True)
  (ReLU): ReLU()
  (output): Linear(in_features=5, out_features=2, bias=True)
  (Sigmoid): Sigmoid()
)
tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])
Epoch 1000 Loss: 0.10040948539972305 Accuracy: 75.0%
Model 2 reached 100% accuracy at epoch 1399
tensor([[0.0548, 0.4086],
        [0.1215, 0.8413],
        [0.1422, 0.5001],
        [0.8434, 0.2482]], grad_fn=<SigmoidBackward0>)
Model Accuracy: 100.0%
Model weights:
hidden.weight tensor([[-0.3056,  1.0651],
        [ 0.1049, -0.1715],
        [ 1.0874,  1.3417],
        [ 0.0040, -0.7903],
        [-1.6600,  1.6602]])
hidden.bias tensor([ 3.0960e-01, -5.2916e-01, -3.5421e-01,  9.1398e-01,  8.0554e-04])
output.weight tensor([[ 0.3987, -0.3546,  1.6042, -1.1473, -1.2337],
        [-0.9371,  0.4234,  0.1126,  0.3336,  1.9222]])
output.bias tensor([-1.9215, -0.3870])


In [158]:
model3 = nn.Sequential(OrderedDict([
    ('hidden', nn.Linear(2, 2)),  
    ('ReLU', nn.ReLU()),    
    ('output', nn.Linear(2, 2)),  
    ('tanh', nn.Tanh())
]))
print(model3)

data_in3 = torch.tensor([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=torch.float)
print(data_in3)

data_target3 = torch.tensor([[0, 0], [0, 1], [0, 1], [1, 0]], dtype=torch.float)
print(data_target3)

criterion3 = nn.MSELoss()
optimizer3 = torch.optim.SGD(model3.parameters(), lr=0.1)

for epoch in range(10000):
    outputs3 = model3(data_in3)
    loss3 = criterion3(outputs3, data_target1)
    
    optimizer3.zero_grad()  
    loss3.backward()          
    optimizer3.step()         
    
    predicted_classes3 = (outputs3.round() == data_target3)
    accuracy3 = predicted_classes3.all(dim=1).sum() / len(data_target3)
    if epoch % 1000 == 0:
        print(f"Epoch {epoch+1}: {accuracy3*100}%")
    if accuracy3 == 1:
        print(f"Model 1 reached 100% accuracy at epoch {epoch+1}")
        break

print(outputs3)
predicted3 = torch.round(outputs3)
correct3 = (predicted3 == data_target3).all(dim=1).sum()
total3 = data_target3.size(0)
accuracy3 = correct3 / total3
print(f'Model Accuracy: {accuracy3*100}%')  

    
print(f"Model weights:")
for name, param in model3.named_parameters():
    if param.requires_grad:
        print(name, param.data)

Sequential(
  (hidden): Linear(in_features=2, out_features=2, bias=True)
  (ReLU): ReLU()
  (output): Linear(in_features=2, out_features=2, bias=True)
  (tanh): Tanh()
)
tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 1.],
        [0., 1.],
        [1., 0.]])
Epoch 1: 25.0%
Epoch 1001: 25.0%
Epoch 2001: 25.0%
Epoch 3001: 25.0%
Epoch 4001: 25.0%
Epoch 5001: 25.0%
Epoch 6001: 25.0%
Epoch 7001: 25.0%
Epoch 8001: 25.0%
Epoch 9001: 25.0%
tensor([[0.2500, 0.5000],
        [0.2500, 0.5000],
        [0.2500, 0.5000],
        [0.2500, 0.5000]], grad_fn=<TanhBackward0>)
Model Accuracy: 25.0%
Model weights:
hidden.weight tensor([[-0.4749,  0.1620],
        [-0.1329,  0.0828]])
hidden.bias tensor([-0.1642, -0.6107])
output.weight tensor([[ 0.6215, -0.0772],
        [ 0.1837, -0.4338]])
output.bias tensor([0.2554, 0.5493])
